CREATE TABLE teams (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(255),
  stadium VARCHAR(255),
  founded_year INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE players (
  id BIGSERIAL PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  position VARCHAR(100),
  birth_date DATE,
  nationality VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE matches (
  id BIGSERIAL PRIMARY KEY,
  home_team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
  away_team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
  match_date TIMESTAMP WITH TIME ZONE NOT NULL,
  venue VARCHAR(255),
  home_score INTEGER DEFAULT 0 NOT NULL,
  away_score INTEGER DEFAULT 0 NOT NULL,
  home_possession NUMERIC(5,2),
  away_possession NUMERIC(5,2),
  home_xg NUMERIC(5,2),
  away_xg NUMERIC(5,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CHECK (home_team_id <> away_team_id)
);

CREATE TABLE trophies (
  id BIGSERIAL PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  competition_name VARCHAR(255) NOT NULL,
  season VARCHAR(20),
  awarded_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE player_season_stats (
  id BIGSERIAL PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  season VARCHAR(20) NOT NULL,
  appearances INTEGER DEFAULT 0 NOT NULL,
  starts INTEGER DEFAULT 0 NOT NULL,
  minutes_played INTEGER DEFAULT 0 NOT NULL,
  goals INTEGER DEFAULT 0 NOT NULL,
  assists INTEGER DEFAULT 0 NOT NULL,
  yellow_cards INTEGER DEFAULT 0 NOT NULL,
  red_cards INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE (player_id, season)
);
